### ISSUE TITLE
BLE Attacks cause crash.

### ISSUE THREAD

**Issue by CC-Army** [Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display#7]
Almost all BLE Spam except sour apple seem to crash pretty quickly. Has anybody found a solution so far?

**Comment by Fr4nkFletcher** [comment]
> Almost all BLE Spam except sour apple seem to crash pretty quickly. Has anybody found a solution so far?

Working on this, hoping to have completed this weekend

**Comment by Matt8619** [comment]
Almost all ble crashes and scan AP crashes after about 30 seconds

**Comment by namara624** [comment]
any thing new? i thought it was a power drain issue. im not sure i think it kinda happens if there is alot of device around. i tried it out in kinda an enclsoed area and it worked a little bit longer but crashed none the less. are there logs for this?

**Comment by Matt8619** [comment]
So there is definitely an issue that causes the bluetooth attacks to crash. After testing I've notice that if you stop scan ap after about 30 seconds it does not crash.

**Comment by Bryplak** [comment]
Please update the installer to 13.9. That should fix the ble spam issue.

**Comment by Fr4nkFletcher** [comment]
> Please update the installer to 13.9. That should fix the ble spam issue. 

How so? I thought most of the changes were for the marauder mini. I'm trying to fix this but so far I've failed

**Comment by smoochiee** [comment]
> > Please update the installer to 13.9. That should fix the ble spam issue. 
> 
> How so? I thought most of the changes were for the marauder mini. I'm trying to fix this but so far I've failed

Its not fix in 13.9

**Comment by Fr4nkFletcher** [comment]
Should be somewhat fixed

**Comment by Fr4nkFletcher** [comment]
> > > Please update the installer to 13.9. That should fix the ble spam issue. 
> > 
> > How so? I thought most of the changes were for the marauder mini. I'm trying to fix this but so far I've failed
> 
> Its not fix in 13.9 ive tested it..

To clarify, Smoochiee is saying the BLE spam issue is not fixed/changed whatsoever in JustCallMeKoko's 0.13.9 release.

The current release in the Cheap-Yellow-Marauder webflasher however does have the fix. Another delay in executeSwiftPair had to be added, along with the delay already in place had to be increased to 1000ms. The fix is not 100% in all cases but is a definite improvement.

**Comment by CC-Army** [comment]
Great job. BLE spam works much better now.
unfortunately Wifi Sniffing with GPS seems to crash now instantly. Without GPS it works fine.

**Comment by Fr4nkFletcher** [comment]
> Great job. BLE spam works much better now.
> unfortunately Wifi Sniffing with GPS seems to crash now instantly. Without GPS it works fine.

Good deal. Thanks for letting me know about that, I'll get it right

**Comment by Fr4nkFletcher** [comment]
> Great job. BLE spam works much better now. unfortunately Wifi Sniffing with GPS seems to crash now instantly. Without GPS it works fine.

I just tested every option on WiFi Sniffers, Micro-USB only and CYD2USB, w/ GPS and w/o, and could not make it crash. Jump on the [CYD discord](https://discord.gg/nnezpvq), search my username and PM me please

**Comment by Fr4nkFletcher** [comment]
> Great job. BLE spam works much better now. unfortunately Wifi Sniffing with GPS seems to crash now instantly. Without GPS it works fine.

I see now Wardrive crashes it. I'll get it fixed

**Comment by Fr4nkFletcher** [comment]
> Great job. BLE spam works much better now. unfortunately Wifi Sniffing with GPS seems to crash now instantly. Without GPS it works fine.

Just tested, and you're right. I'm not sure what happened but I'll get it
